# Name & region
project_name: demo-vpc-private
region: eu-west-2           # London
az: eu-west-2a

# Networking (private only)
vpc_cidr: 10.42.0.0/16
private_subnet_cidr: 10.42.11.0/24

# EC2
instance_type: t3.micro
ami_id: ""                  # leave blank to auto-pick latest AL2023 x86_64

# Endpoints (keep true for a no-internet, SSM-only setup)
enable_vpc_endpoints: true
endpoint_services:
  - ssm
  - ec2messages
  - ssmmessages
enable_s3_gateway_endpoint: true    # good for SSM agent & packages without internet
enable_cloudwatch_logs_endpoint: false
enable_kms_endpoint: false